### ISSUE TITLE
Create Team PR

### ISSUE THREAD

**Issue by PotatoCombat** [AY1920S2-CS2103T-W17-4/main#3]
**TODO**
- [x] Decide on a product name
- [x] Create team PR from master to the 2103 repo
- [x] @mention team members in PR (for tutor notifications)

**Notes:**
The following should be the title of the PR
[CS2103T-TW17-4] Product Name
