### ISSUE TITLE
Draft rough project plan

### ISSUE THREAD

**Issue by PotatoCombat** [AY1920S2-CS2103T-W17-4/main#70]
- [x] Decide on v1.4. enhancements
- [x] Assign enhancements to team members
- [x] Divide each feature into two increments, to be released at v1.2, v1.3
(increment should deliver an end-user visible enhancement)
- [x] Create issues for each increment, and link to respective milestone
- [x] Set deadline for minimal implementations
